use_frameworks!

platform :ios, '9.0'

target 'QXVIP_Example' do
  pod 'QXVIP', :path => '../'

  pod 'MGJRouter', '~> 0.10.0' # 中间件
  
  target 'QXVIP_Tests' do
    inherit! :search_paths

    
  end
end
